FROM wordpress:6
WORKDIR /var/www/html

ARG WORDPRESS_DB_HOST
ENV WORDPRESS_DB_HOST ${WORDPRESS_DB_HOST}

ARG WORDPRESS_DB_USER
ENV WORDPRESS_DB_USER ${WORDPRESS_DB_USER}

ARG WORDPRESS_DB_PASSWORD
ENV WORDPRESS_DB_PASSWORD ${WORDPRESS_DB_PASSWORD}

ARG WORDPRESS_DB_NAME
ENV WORDPRESS_DB_NAME ${WORDPRESS_DB_NAME}

COPY ./wordpress/wp-content ./wp-content

