services:
  db:
    image: mysql:8.0.29
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    links:
      - db
    image: wordpress:6.0.0
    volumes:
      - ./wordpress/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wordpress/wp-content:/var/www/html/wp-content
      - wp_data:/var/www/html
    ports:
      - "4200:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  wpcli:
    image: wordpress:cli
    volumes:
      - ./wordpress/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "wordpress"
    depends_on:
      - db
      - wordpress

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 4201:80
    links:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
      UPLOAD_LIMIT: 64M
    restart: always

volumes:
  db_data: {}
  wp_data: {}
