import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useQuery } from "react-query";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL;

export default function Home() {
  const { isLoading, error, data } = useQuery(["postData"], () =>
    fetch(`${siteUrl}/wp-json/wp/v2/posts`).then((res) => res.json())
  );

  if (error) console.error(error);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Posts:</h2>
        {isLoading && <p>Loading...</p>}
        {!isLoading && !error && data && (
          <ul>
            {data.map((post, idx) => (
              <li key={idx}>{post.title?.rendered}</li>
            ))}
          </ul>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
